# -*- coding: utf-8 -*-
"""L3-2(R-CNN).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uTVMV00bMwz34uzA_hRRjTnYeRb1dy4C

# 🔍 Faster R-CNN Object Detection
### ResNet50 backbone · COCO 2017 · TensorFlow Hub

---

## 📋 Overview
This notebook runs **real Faster R-CNN inference** on a custom image using Google's
pre-trained ResNet50 model served via TF-Hub. It detects up to **90 COCO object classes**
and draws colour-coded bounding boxes with labels and confidence scores.

---

## 🏗️ Pipeline

| Step | Description |
|------|-------------|
| **1. Load Model** | Downloads Faster R-CNN ResNet50 v1 (640×640) from TF-Hub |
| **2. Preprocess** | Reads image with OpenCV → converts BGR → RGB → `uint8` tensor `[1, H, W, 3]` |
| **3. Inference** | Model runs RPN → ROI Align → NMS internally and returns raw detections |
| **4. Filter** | Keeps only detections above `MIN_CONF` threshold (default: **50%**) |
| **5. Visualise** | Draws bounding boxes with unique colours + saves output as `.jpg` |

---

## ⚙️ Configuration

| Variable | Default | Description |
|----------|---------|-------------|
| `IMAGE_PATH` | `/content/...webp` | Path to your input image |
| `MIN_CONF` | `0.50` | Minimum confidence score (0–1) |
| `OUTPUT_PATH` | `detection_output.jpg` | Where to save the annotated image |

> 💡 **Tip:** Lower `MIN_CONF` to `0.30` to catch more objects; raise it to `0.70` for higher precision.

---

## 📦 Dependencies
````python
tensorflow  tensorflow-hub  opencv-python  matplotlib  numpy
````

> Install in Colab: `!pip install tensorflow tensorflow-hub opencv-python-headless`

---

## 🗂️ COCO Classes Detected
This model recognises **90 object categories** including:
`person · car · bottle · cup · chair · laptop · cell phone · dog · cat`
and 81 more from the [COCO 2017 dataset](https://cocodataset.org/#explore).

---
"""

# ============================================================
# Faster R-CNN Object Detection (Google COCO Model)
# ============================================================
import tensorflow as tf
import tensorflow_hub as hub
import cv2
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as patches
import os

# ── COCO 2017 label map (91 classes, indices 1-90) ──────────
COCO_LABELS = {
    1:"person",2:"bicycle",3:"car",4:"motorcycle",5:"airplane",
    6:"bus",7:"train",8:"truck",9:"boat",10:"traffic light",
    11:"fire hydrant",13:"stop sign",14:"parking meter",15:"bench",
    16:"bird",17:"cat",18:"dog",19:"horse",20:"sheep",21:"cow",
    22:"elephant",23:"bear",24:"zebra",25:"giraffe",27:"backpack",
    28:"umbrella",31:"handbag",32:"tie",33:"suitcase",34:"frisbee",
    35:"skis",36:"snowboard",37:"sports ball",38:"kite",39:"baseball bat",
    40:"baseball glove",41:"skateboard",42:"surfboard",43:"tennis racket",
    44:"bottle",46:"wine glass",47:"cup",48:"fork",49:"knife",50:"spoon",
    51:"bowl",52:"banana",53:"apple",54:"sandwich",55:"orange",
    56:"broccoli",57:"carrot",58:"hot dog",59:"pizza",60:"donut",
    61:"cake",62:"chair",63:"couch",64:"potted plant",65:"bed",
    67:"dining table",70:"toilet",72:"tv",73:"laptop",74:"mouse",
    75:"remote",76:"keyboard",77:"cell phone",78:"microwave",79:"oven",
    80:"toaster",81:"sink",82:"refrigerator",84:"book",85:"clock",
    86:"vase",87:"scissors",88:"teddy bear",89:"hair drier",90:"toothbrush"
}

# ── CONFIG ───────────────────────────────────────────────────
IMAGE_PATH    = "/content/shutterstock_1723731022.jpg"   # ← change if needed
MIN_CONF      = 0.20    # minimum confidence threshold (0–1)
OUTPUT_PATH   = "detection_output.jpg"

# ── 1. LOAD MODEL ────────────────────────────────────────────
print("Loading Faster R-CNN ResNet50 from TF-Hub …")
MODEL_URL = "https://tfhub.dev/tensorflow/faster_rcnn/resnet50_v1_640x640/1"
detector  = hub.load(MODEL_URL)
print("✓ Model ready.\n")

# ── 2. LOAD & PREPROCESS IMAGE ───────────────────────────────
assert os.path.exists(IMAGE_PATH), f"File not found: {IMAGE_PATH}"

img_bgr = cv2.imread(IMAGE_PATH)
assert img_bgr is not None, "cv2.imread failed – check file format/path."
img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
h, w    = img_rgb.shape[:2]

# Model expects uint8 tensor of shape [1, H, W, 3]
inp = tf.expand_dims(tf.constant(img_rgb, dtype=tf.uint8), 0)

# ── 3. INFERENCE ─────────────────────────────────────────────
print("Running inference …")
raw = detector(inp)
print("✓ Inference complete.\n")

# Unpack all relevant tensors (squeeze batch dim)
boxes   = raw["detection_boxes"][0].numpy()          # [N, 4] ymin xmin ymax xmax (normalised)
scores  = raw["detection_scores"][0].numpy()         # [N]
classes = raw["detection_classes"][0].numpy().astype(int)  # [N]

# ── 4. FILTER BY CONFIDENCE ──────────────────────────────────
mask       = scores >= MIN_CONF
f_boxes    = boxes[mask]
f_scores   = scores[mask]
f_classes  = classes[mask]

print(f"Detections above {MIN_CONF*100:.0f}% confidence: {len(f_boxes)}")
for i, (cls, sc) in enumerate(zip(f_classes, f_scores)):
    label = COCO_LABELS.get(cls, f"class_{cls}")
    print(f"  [{i+1}] {label:20s}  {sc*100:.1f}%")

# ── 5. VISUALISE ─────────────────────────────────────────────
fig, ax = plt.subplots(1, figsize=(14, 9))
ax.imshow(img_rgb)

COLORS = plt.cm.get_cmap("tab20", max(len(f_boxes), 1))

for i, (box, score, cls) in enumerate(zip(f_boxes, f_scores, f_classes)):
    ymin, xmin, ymax, xmax = box
    x1, y1 = int(xmin * w), int(ymin * h)
    bw, bh  = int((xmax - xmin) * w), int((ymax - ymin) * h)

    color = COLORS(i % 20)
    label = COCO_LABELS.get(cls, f"cls {cls}")

    rect = patches.Rectangle((x1, y1), bw, bh,
                              linewidth=2.5, edgecolor=color, facecolor="none")
    ax.add_patch(rect)
    ax.text(x1, max(y1 - 6, 0), f"{label}  {score*100:.0f}%",
            color="white", fontsize=9, fontweight="bold",
            bbox=dict(boxstyle="round,pad=0.2", facecolor=color, alpha=0.85, edgecolor="none"))

ax.set_title(f"Faster R-CNN  |  {len(f_boxes)} detections  (conf ≥ {MIN_CONF*100:.0f}%)",
             fontsize=14, pad=12)
ax.axis("off")
plt.tight_layout()
plt.savefig(OUTPUT_PATH, dpi=150, bbox_inches="tight")
plt.show()
print(f"\n✓ Saved → {OUTPUT_PATH}")